# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-24 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecode',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
