# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-24 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIApp', '0003_auto_20170324_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecode',
            name='code',
            field=models.IntegerField(max_length=20),
        ),
    ]
